AWSTemplateFormatVersion: '2010-09-09'
Description: Create an Amazon EKS cluster with a node group.
Resources:
  EKSCluster:
    Type: 'AWS::EKS::Cluster'
    Properties:
      Name: str8d-cluster-demo-CF
      Version: '1.19'
      RoleArn: arn:aws:iam::287330755957:role/str8d-iam-eks-role-demo-CF
      ResourcesVpcConfig:
        SecurityGroupIds:
          - sg-0a1d12016944f4e28
        SubnetIds:
          - subnet-0d39deba4c8aeb530
          - subnet-0f8558ced0ad39b82