AWSTemplateFormatVersion: "2010-09-09"
Resources:
  EKSIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "str8d-IAMRole-cluster-demo-CF"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "eks.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      Tags:
        - Key: "LabName"
          Value: "see tag history for details"
        - Key: "ManagedBy"
          Value: "CloudFormation"

      
  WorkerNodeIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      RoleName: "str8d-IAMRole-workernode-demo-CF"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      - arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilderECRContainerBuilds
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      Tags:
        - Key: "LabName"
          Value: "see tag history for details"
        - Key: "ManagedBy"
          Value: "CloudFormation"