AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      RoleName: "my-iam-role"

  EKSPolicyAttachment:
    Type: "AWS::IAM::PolicyAttachment"
    Properties:
      PolicyArn: "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
      Roles:
        - !Ref MyIAMRole